<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.13" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.*" />
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*" />
    <PackageReference Include="Moq" Version="4.20.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SelfStorageManagementSystem.BusinessLogic\SelfStorageManagementSystem.BusinessLogic.csproj" />
    <ProjectReference Include="..\..\src\SelfStorageManagementSystem.DataAccess\SelfStorageManagementSystem.DataAccess.csproj" />
    <ProjectReference Include="..\..\src\SelfStorageManagementSystem.Presentation\SelfStorageManagementSystem.Presentation.csproj" />
    <ProjectReference Include="..\..\src\SelfStorageManagementSystem.WpfClient\SelfStorageManagementSystem.WpfClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="System.Net.Http" />
    <Using Include="System.Net.Http.Json" />
  </ItemGroup>

</Project>